server:
  port: 33333
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.84.210.174:65432/2023-BBE-1-G4
    username: Backend_2023_G4
    password: 1qaz2wsx
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace